/*-
 * ================================================================================
 * eCOMP Portal SDK
 * ================================================================================
 * Copyright (C) 2017 AT&T Intellectual Property
 * ================================================================================
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ================================================================================
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.07 at 02:07:29 PM EDT 
//


package org.openecomp.portalsdk.analytics.xmlobj;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ChartDrillOptions complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ChartDrillOptions">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="drill_reportId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="drill_xAxis_FormField" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="drill_yAxis_FormField" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="drill_series_FormField" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="targetFormfield" type="{}ChartDrillFormfield" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ChartDrillOptions", propOrder = {
    "drillReportId",
    "drillXAxisFormField",
    "drillYAxisFormField",
    "drillSeriesFormField",
    "targetFormfield"
})
public class ChartDrillOptions {

    @XmlElement(name = "drill_reportId")
    protected String drillReportId;
    @XmlElement(name = "drill_xAxis_FormField")
    protected String drillXAxisFormField;
    @XmlElement(name = "drill_yAxis_FormField")
    protected String drillYAxisFormField;
    @XmlElement(name = "drill_series_FormField")
    protected String drillSeriesFormField;
    protected List<ChartDrillFormfield> targetFormfield;

    /**
     * Gets the value of the drillReportId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDrillReportId() {
        return drillReportId;
    }

    /**
     * Sets the value of the drillReportId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDrillReportId(String value) {
        this.drillReportId = value;
    }

    /**
     * Gets the value of the drillXAxisFormField property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDrillXAxisFormField() {
        return drillXAxisFormField;
    }

    /**
     * Sets the value of the drillXAxisFormField property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDrillXAxisFormField(String value) {
        this.drillXAxisFormField = value;
    }

    /**
     * Gets the value of the drillYAxisFormField property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDrillYAxisFormField() {
        return drillYAxisFormField;
    }

    /**
     * Sets the value of the drillYAxisFormField property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDrillYAxisFormField(String value) {
        this.drillYAxisFormField = value;
    }

    /**
     * Gets the value of the drillSeriesFormField property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDrillSeriesFormField() {
        return drillSeriesFormField;
    }

    /**
     * Sets the value of the drillSeriesFormField property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDrillSeriesFormField(String value) {
        this.drillSeriesFormField = value;
    }

    /**
     * Gets the value of the targetFormfield property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the targetFormfield property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTargetFormfield().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ChartDrillFormfield }
     * 
     * 
     */
    public List<ChartDrillFormfield> getTargetFormfield() {
        if (targetFormfield == null) {
            targetFormfield = new ArrayList<ChartDrillFormfield>();
        }
        return this.targetFormfield;
    }

}
