/*-
 * ================================================================================
 * ECOMP Portal SDK
 * ================================================================================
 * Copyright (C) 2017 AT&T Intellectual Property
 * ================================================================================
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ================================================================================
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.07 at 02:07:29 PM EDT 
//


package org.openecomp.portalsdk.analytics.xmlobj;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ChartAdditionalOptions complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ChartAdditionalOptions">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="chartMultiplePieOrder" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="chartMultiplePieLabelDisplay" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="chartOrientation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="secondaryChartRenderer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="chartDisplay" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="hideToolTips" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="hidechartLegend" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="legendPosition" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="labelAngle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="intervalFromdate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="intervalTodate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="intervalLabel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="lastSeriesALineChart" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="lastSeriesABarChart" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="maxLabelsInDomainAxis" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="linearRegression" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="linearRegressionColor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="exponentialRegressionColor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="maxRegression" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="rangeAxisUpperLimit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="rangeAxisLowerLimit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="overlayItemValueOnStackBar" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="animate" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="animateAnimatedChart" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="keepDomainAxisValueAsString" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="stacked" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="barControls" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="xAxisDateType" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="lessXaxisTickers" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="timeAxis" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="timeSeriesRender" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="multiSeries" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="showXAxisLabel" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="addXAxisTickers" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="zoomIn" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="timeAxisType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="logScale" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="topMargin" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="bottomMargin" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="rightMargin" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="leftMargin" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ChartAdditionalOptions", propOrder = {
    "chartMultiplePieOrder",
    "chartMultiplePieLabelDisplay",
    "chartOrientation",
    "secondaryChartRenderer",
    "chartDisplay",
    "hideToolTips",
    "hidechartLegend",
    "legendPosition",
    "labelAngle",
    "intervalFromdate",
    "intervalTodate",
    "intervalLabel",
    "lastSeriesALineChart",
    "lastSeriesABarChart",
    "maxLabelsInDomainAxis",
    "linearRegression",
    "linearRegressionColor",
    "exponentialRegressionColor",
    "maxRegression",
    "rangeAxisUpperLimit",
    "rangeAxisLowerLimit",
    "overlayItemValueOnStackBar",
    "animate",
    "animateAnimatedChart",
    "keepDomainAxisValueAsString",
    "stacked",
    "barControls",
    "xAxisDateType",
    "lessXaxisTickers",
    "timeAxis",
    "timeSeriesRender",
    "multiSeries",
    "showXAxisLabel",
    "addXAxisTickers",
    "zoomIn",
    "timeAxisType",
    "logScale",
    "topMargin",
    "bottomMargin",
    "rightMargin",
    "leftMargin"
})
public class ChartAdditionalOptions {

    protected String chartMultiplePieOrder;
    protected String chartMultiplePieLabelDisplay;
    protected String chartOrientation;
    protected String secondaryChartRenderer;
    protected String chartDisplay;
    protected String hideToolTips;
    protected String hidechartLegend;
    protected String legendPosition;
    protected String labelAngle;
    protected String intervalFromdate;
    protected String intervalTodate;
    protected String intervalLabel;
    protected String lastSeriesALineChart;
    protected String lastSeriesABarChart;
    protected String maxLabelsInDomainAxis;
    protected String linearRegression;
    protected String linearRegressionColor;
    protected String exponentialRegressionColor;
    protected String maxRegression;
    protected String rangeAxisUpperLimit;
    protected String rangeAxisLowerLimit;
    protected String overlayItemValueOnStackBar;
    @XmlElement(defaultValue = "false")
    protected Boolean animate;
    @XmlElement(defaultValue = "true")
    protected Boolean animateAnimatedChart;
    protected String keepDomainAxisValueAsString;
    @XmlElement(defaultValue = "false")
    protected Boolean stacked;
    @XmlElement(defaultValue = "false")
    protected Boolean barControls;
    @XmlElement(defaultValue = "false")
    protected Boolean xAxisDateType;
    @XmlElement(defaultValue = "false")
    protected Boolean lessXaxisTickers;
    @XmlElement(defaultValue = "true")
    protected Boolean timeAxis;
    protected String timeSeriesRender;
    @XmlElement(defaultValue = "false")
    protected Boolean multiSeries;
    @XmlElement(defaultValue = "false")
    protected Boolean showXAxisLabel;
    @XmlElement(defaultValue = "false")
    protected Boolean addXAxisTickers;
    protected Integer zoomIn;
    protected String timeAxisType;
    @XmlElement(defaultValue = "false")
    protected Boolean logScale;
    protected Integer topMargin;
    protected Integer bottomMargin;
    protected Integer rightMargin;
    protected Integer leftMargin;

    /**
     * Gets the value of the chartMultiplePieOrder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChartMultiplePieOrder() {
        return chartMultiplePieOrder;
    }

    /**
     * Sets the value of the chartMultiplePieOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChartMultiplePieOrder(String value) {
        this.chartMultiplePieOrder = value;
    }

    /**
     * Gets the value of the chartMultiplePieLabelDisplay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChartMultiplePieLabelDisplay() {
        return chartMultiplePieLabelDisplay;
    }

    /**
     * Sets the value of the chartMultiplePieLabelDisplay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChartMultiplePieLabelDisplay(String value) {
        this.chartMultiplePieLabelDisplay = value;
    }

    /**
     * Gets the value of the chartOrientation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChartOrientation() {
        return chartOrientation;
    }

    /**
     * Sets the value of the chartOrientation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChartOrientation(String value) {
        this.chartOrientation = value;
    }

    /**
     * Gets the value of the secondaryChartRenderer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecondaryChartRenderer() {
        return secondaryChartRenderer;
    }

    /**
     * Sets the value of the secondaryChartRenderer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecondaryChartRenderer(String value) {
        this.secondaryChartRenderer = value;
    }

    /**
     * Gets the value of the chartDisplay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChartDisplay() {
        return chartDisplay;
    }

    /**
     * Sets the value of the chartDisplay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChartDisplay(String value) {
        this.chartDisplay = value;
    }

    /**
     * Gets the value of the hideToolTips property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHideToolTips() {
        return hideToolTips;
    }

    /**
     * Sets the value of the hideToolTips property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHideToolTips(String value) {
        this.hideToolTips = value;
    }

    /**
     * Gets the value of the hidechartLegend property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHidechartLegend() {
        return hidechartLegend;
    }

    /**
     * Sets the value of the hidechartLegend property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHidechartLegend(String value) {
        this.hidechartLegend = value;
    }

    /**
     * Gets the value of the legendPosition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegendPosition() {
        return legendPosition;
    }

    /**
     * Sets the value of the legendPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegendPosition(String value) {
        this.legendPosition = value;
    }

    /**
     * Gets the value of the labelAngle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabelAngle() {
        return labelAngle;
    }

    /**
     * Sets the value of the labelAngle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabelAngle(String value) {
        this.labelAngle = value;
    }

    /**
     * Gets the value of the intervalFromdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntervalFromdate() {
        return intervalFromdate;
    }

    /**
     * Sets the value of the intervalFromdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntervalFromdate(String value) {
        this.intervalFromdate = value;
    }

    /**
     * Gets the value of the intervalTodate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntervalTodate() {
        return intervalTodate;
    }

    /**
     * Sets the value of the intervalTodate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntervalTodate(String value) {
        this.intervalTodate = value;
    }

    /**
     * Gets the value of the intervalLabel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntervalLabel() {
        return intervalLabel;
    }

    /**
     * Sets the value of the intervalLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntervalLabel(String value) {
        this.intervalLabel = value;
    }

    /**
     * Gets the value of the lastSeriesALineChart property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastSeriesALineChart() {
        return lastSeriesALineChart;
    }

    /**
     * Sets the value of the lastSeriesALineChart property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastSeriesALineChart(String value) {
        this.lastSeriesALineChart = value;
    }

    /**
     * Gets the value of the lastSeriesABarChart property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastSeriesABarChart() {
        return lastSeriesABarChart;
    }

    /**
     * Sets the value of the lastSeriesABarChart property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastSeriesABarChart(String value) {
        this.lastSeriesABarChart = value;
    }

    /**
     * Gets the value of the maxLabelsInDomainAxis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxLabelsInDomainAxis() {
        return maxLabelsInDomainAxis;
    }

    /**
     * Sets the value of the maxLabelsInDomainAxis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxLabelsInDomainAxis(String value) {
        this.maxLabelsInDomainAxis = value;
    }

    /**
     * Gets the value of the linearRegression property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinearRegression() {
        return linearRegression;
    }

    /**
     * Sets the value of the linearRegression property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinearRegression(String value) {
        this.linearRegression = value;
    }

    /**
     * Gets the value of the linearRegressionColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinearRegressionColor() {
        return linearRegressionColor;
    }

    /**
     * Sets the value of the linearRegressionColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinearRegressionColor(String value) {
        this.linearRegressionColor = value;
    }

    /**
     * Gets the value of the exponentialRegressionColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExponentialRegressionColor() {
        return exponentialRegressionColor;
    }

    /**
     * Sets the value of the exponentialRegressionColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExponentialRegressionColor(String value) {
        this.exponentialRegressionColor = value;
    }

    /**
     * Gets the value of the maxRegression property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxRegression() {
        return maxRegression;
    }

    /**
     * Sets the value of the maxRegression property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxRegression(String value) {
        this.maxRegression = value;
    }

    /**
     * Gets the value of the rangeAxisUpperLimit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRangeAxisUpperLimit() {
        return rangeAxisUpperLimit;
    }

    /**
     * Sets the value of the rangeAxisUpperLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRangeAxisUpperLimit(String value) {
        this.rangeAxisUpperLimit = value;
    }

    /**
     * Gets the value of the rangeAxisLowerLimit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRangeAxisLowerLimit() {
        return rangeAxisLowerLimit;
    }

    /**
     * Sets the value of the rangeAxisLowerLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRangeAxisLowerLimit(String value) {
        this.rangeAxisLowerLimit = value;
    }

    /**
     * Gets the value of the overlayItemValueOnStackBar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOverlayItemValueOnStackBar() {
        return overlayItemValueOnStackBar;
    }

    /**
     * Sets the value of the overlayItemValueOnStackBar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOverlayItemValueOnStackBar(String value) {
        this.overlayItemValueOnStackBar = value;
    }

    /**
     * Gets the value of the animate property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAnimate() {
        return animate;
    }

    /**
     * Sets the value of the animate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAnimate(Boolean value) {
        this.animate = value;
    }

    /**
     * Gets the value of the animateAnimatedChart property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAnimateAnimatedChart() {
        return animateAnimatedChart;
    }

    /**
     * Sets the value of the animateAnimatedChart property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAnimateAnimatedChart(Boolean value) {
        this.animateAnimatedChart = value;
    }

    /**
     * Gets the value of the keepDomainAxisValueAsString property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeepDomainAxisValueAsString() {
        return keepDomainAxisValueAsString;
    }

    /**
     * Sets the value of the keepDomainAxisValueAsString property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeepDomainAxisValueAsString(String value) {
        this.keepDomainAxisValueAsString = value;
    }

    /**
     * Gets the value of the stacked property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isStacked() {
        return stacked;
    }

    /**
     * Sets the value of the stacked property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setStacked(Boolean value) {
        this.stacked = value;
    }

    /**
     * Gets the value of the barControls property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBarControls() {
        return barControls;
    }

    /**
     * Sets the value of the barControls property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBarControls(Boolean value) {
        this.barControls = value;
    }

    /**
     * Gets the value of the xAxisDateType property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isXAxisDateType() {
        return xAxisDateType;
    }

    /**
     * Sets the value of the xAxisDateType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setXAxisDateType(Boolean value) {
        this.xAxisDateType = value;
    }

    /**
     * Gets the value of the lessXaxisTickers property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLessXaxisTickers() {
        return lessXaxisTickers;
    }

    /**
     * Sets the value of the lessXaxisTickers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLessXaxisTickers(Boolean value) {
        this.lessXaxisTickers = value;
    }

    /**
     * Gets the value of the timeAxis property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTimeAxis() {
        return timeAxis;
    }

    /**
     * Sets the value of the timeAxis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTimeAxis(Boolean value) {
        this.timeAxis = value;
    }

    /**
     * Gets the value of the timeSeriesRender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeSeriesRender() {
        return timeSeriesRender;
    }

    /**
     * Sets the value of the timeSeriesRender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeSeriesRender(String value) {
        this.timeSeriesRender = value;
    }

    /**
     * Gets the value of the multiSeries property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isMultiSeries() {
        return multiSeries;
    }

    /**
     * Sets the value of the multiSeries property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMultiSeries(Boolean value) {
        this.multiSeries = value;
    }

    /**
     * Gets the value of the showXAxisLabel property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isShowXAxisLabel() {
        return showXAxisLabel;
    }

    /**
     * Sets the value of the showXAxisLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShowXAxisLabel(Boolean value) {
        this.showXAxisLabel = value;
    }

    /**
     * Gets the value of the addXAxisTickers property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAddXAxisTickers() {
        return addXAxisTickers;
    }

    /**
     * Sets the value of the addXAxisTickers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAddXAxisTickers(Boolean value) {
        this.addXAxisTickers = value;
    }

    /**
     * Gets the value of the zoomIn property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getZoomIn() {
        return zoomIn;
    }

    /**
     * Sets the value of the zoomIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setZoomIn(Integer value) {
        this.zoomIn = value;
    }

    /**
     * Gets the value of the timeAxisType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeAxisType() {
        return timeAxisType;
    }

    /**
     * Sets the value of the timeAxisType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeAxisType(String value) {
        this.timeAxisType = value;
    }

    /**
     * Gets the value of the logScale property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLogScale() {
        return logScale;
    }

    /**
     * Sets the value of the logScale property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLogScale(Boolean value) {
        this.logScale = value;
    }

    /**
     * Gets the value of the topMargin property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTopMargin() {
        return topMargin;
    }

    /**
     * Sets the value of the topMargin property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTopMargin(Integer value) {
        this.topMargin = value;
    }

    /**
     * Gets the value of the bottomMargin property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getBottomMargin() {
        return bottomMargin;
    }

    /**
     * Sets the value of the bottomMargin property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setBottomMargin(Integer value) {
        this.bottomMargin = value;
    }

    /**
     * Gets the value of the rightMargin property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRightMargin() {
        return rightMargin;
    }

    /**
     * Sets the value of the rightMargin property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRightMargin(Integer value) {
        this.rightMargin = value;
    }

    /**
     * Gets the value of the leftMargin property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLeftMargin() {
        return leftMargin;
    }

    /**
     * Sets the value of the leftMargin property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLeftMargin(Integer value) {
        this.leftMargin = value;
    }

}
