/*-
 * ================================================================================
 * eCOMP Portal SDK
 * ================================================================================
 * Copyright (C) 2017 AT&T Intellectual Property
 * ================================================================================
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ================================================================================
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.07 at 02:07:29 PM EDT 
//


package org.openecomp.portalsdk.analytics.xmlobj;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.openecomp.portalsdk.analytics.xmlobj package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CustomReport_QNAME = new QName("", "customReport");
    private final static QName _Comment_QNAME = new QName("", "comment");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.openecomp.portalsdk.analytics.xmlobj
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CustomReportType }
     * 
     */
    public CustomReportType createCustomReportType() {
        return new CustomReportType();
    }

    /**
     * Create an instance of {@link ChartAdditionalOptions }
     * 
     */
    public ChartAdditionalOptions createChartAdditionalOptions() {
        return new ChartAdditionalOptions();
    }

    /**
     * Create an instance of {@link DataminingOptions }
     * 
     */
    public DataminingOptions createDataminingOptions() {
        return new DataminingOptions();
    }

    /**
     * Create an instance of {@link FormFieldType }
     * 
     */
    public FormFieldType createFormFieldType() {
        return new FormFieldType();
    }

    /**
     * Create an instance of {@link PredefinedValueList }
     * 
     */
    public PredefinedValueList createPredefinedValueList() {
        return new PredefinedValueList();
    }

    /**
     * Create an instance of {@link DashboardEditorReport }
     * 
     */
    public DashboardEditorReport createDashboardEditorReport() {
        return new DashboardEditorReport();
    }

    /**
     * Create an instance of {@link DataSourceList }
     * 
     */
    public DataSourceList createDataSourceList() {
        return new DataSourceList();
    }

    /**
     * Create an instance of {@link DashboardReports }
     * 
     */
    public DashboardReports createDashboardReports() {
        return new DashboardReports();
    }

    /**
     * Create an instance of {@link ReportMap }
     * 
     */
    public ReportMap createReportMap() {
        return new ReportMap();
    }

    /**
     * Create an instance of {@link FormatList }
     * 
     */
    public FormatList createFormatList() {
        return new FormatList();
    }

    /**
     * Create an instance of {@link JavascriptList }
     * 
     */
    public JavascriptList createJavascriptList() {
        return new JavascriptList();
    }

    /**
     * Create an instance of {@link JavascriptItemType }
     * 
     */
    public JavascriptItemType createJavascriptItemType() {
        return new JavascriptItemType();
    }

    /**
     * Create an instance of {@link DataColumnType }
     * 
     */
    public DataColumnType createDataColumnType() {
        return new DataColumnType();
    }

    /**
     * Create an instance of {@link DataSourceType }
     * 
     */
    public DataSourceType createDataSourceType() {
        return new DataSourceType();
    }

    /**
     * Create an instance of {@link DashboardEditorList }
     * 
     */
    public DashboardEditorList createDashboardEditorList() {
        return new DashboardEditorList();
    }

    /**
     * Create an instance of {@link SemaphoreList }
     * 
     */
    public SemaphoreList createSemaphoreList() {
        return new SemaphoreList();
    }

    /**
     * Create an instance of {@link ColFilterType }
     * 
     */
    public ColFilterType createColFilterType() {
        return new ColFilterType();
    }

    /**
     * Create an instance of {@link ChartDrillOptions }
     * 
     */
    public ChartDrillOptions createChartDrillOptions() {
        return new ChartDrillOptions();
    }

    /**
     * Create an instance of {@link DashboardReportsNew }
     * 
     */
    public DashboardReportsNew createDashboardReportsNew() {
        return new DashboardReportsNew();
    }

    /**
     * Create an instance of {@link ChartDrillFormfield }
     * 
     */
    public ChartDrillFormfield createChartDrillFormfield() {
        return new ChartDrillFormfield();
    }

    /**
     * Create an instance of {@link PDFAdditionalOptions }
     * 
     */
    public PDFAdditionalOptions createPDFAdditionalOptions() {
        return new PDFAdditionalOptions();
    }

    /**
     * Create an instance of {@link Reports }
     * 
     */
    public Reports createReports() {
        return new Reports();
    }

    /**
     * Create an instance of {@link Marker }
     * 
     */
    public Marker createMarker() {
        return new Marker();
    }

    /**
     * Create an instance of {@link FormatType }
     * 
     */
    public FormatType createFormatType() {
        return new FormatType();
    }

    /**
     * Create an instance of {@link DataColumnList }
     * 
     */
    public DataColumnList createDataColumnList() {
        return new DataColumnList();
    }

    /**
     * Create an instance of {@link FormFieldList }
     * 
     */
    public FormFieldList createFormFieldList() {
        return new FormFieldList();
    }

    /**
     * Create an instance of {@link SemaphoreType }
     * 
     */
    public SemaphoreType createSemaphoreType() {
        return new SemaphoreType();
    }

    /**
     * Create an instance of {@link ColFilterList }
     * 
     */
    public ColFilterList createColFilterList() {
        return new ColFilterList();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CustomReportType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "customReport")
    public JAXBElement<CustomReportType> createCustomReport(CustomReportType value) {
        return new JAXBElement<CustomReportType>(_CustomReport_QNAME, CustomReportType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "comment")
    public JAXBElement<String> createComment(String value) {
        return new JAXBElement<String>(_Comment_QNAME, String.class, null, value);
    }

}
