/*-
 * ================================================================================
 * ECOMP Portal SDK
 * ================================================================================
 * Copyright (C) 2017 AT&T Intellectual Property
 * ================================================================================
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ================================================================================
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.07 at 02:07:29 PM EDT 
//


package org.openecomp.portalsdk.analytics.xmlobj;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SemaphoreType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SemaphoreType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="semaphoreName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="semaphoreType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{}comment" minOccurs="0"/>
 *         &lt;element name="target" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="formatList" type="{}FormatList"/>
 *       &lt;/sequence>
 *       &lt;attribute name="semaphoreId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SemaphoreType", propOrder = {
    "semaphoreName",
    "semaphoreType",
    "comment",
    "target",
    "formatList"
})
public class SemaphoreType {

    @XmlElement(required = true)
    protected String semaphoreName;
    @XmlElement(required = true)
    protected String semaphoreType;
    protected String comment;
    @XmlElement(required = true)
    protected String target;
    @XmlElement(required = true)
    protected FormatList formatList;
    @XmlAttribute(name = "semaphoreId")
    protected String semaphoreId;

    /**
     * Gets the value of the semaphoreName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSemaphoreName() {
        return semaphoreName;
    }

    /**
     * Sets the value of the semaphoreName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSemaphoreName(String value) {
        this.semaphoreName = value;
    }

    /**
     * Gets the value of the semaphoreType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSemaphoreType() {
        return semaphoreType;
    }

    /**
     * Sets the value of the semaphoreType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSemaphoreType(String value) {
        this.semaphoreType = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }

    /**
     * Gets the value of the target property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTarget() {
        return target;
    }

    /**
     * Sets the value of the target property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTarget(String value) {
        this.target = value;
    }

    /**
     * Gets the value of the formatList property.
     * 
     * @return
     *     possible object is
     *     {@link FormatList }
     *     
     */
    public FormatList getFormatList() {
        return formatList;
    }

    /**
     * Sets the value of the formatList property.
     * 
     * @param value
     *     allowed object is
     *     {@link FormatList }
     *     
     */
    public void setFormatList(FormatList value) {
        this.formatList = value;
    }

    /**
     * Gets the value of the semaphoreId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSemaphoreId() {
        return semaphoreId;
    }

    /**
     * Sets the value of the semaphoreId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSemaphoreId(String value) {
        this.semaphoreId = value;
    }

}
