/*-
 * ================================================================================
 * eCOMP Portal SDK
 * ================================================================================
 * Copyright (C) 2017 AT&T Intellectual Property
 * ================================================================================
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ================================================================================
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.07 at 02:07:29 PM EDT 
//


package org.openecomp.portalsdk.analytics.xmlobj;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ReportMap complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReportMap">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="markerColor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="useDefaultSize" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="height" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="width" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="isMapAllowedYN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="addAddressInDataYN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="addressColumn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dataColumn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="defaultMapType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="latColumn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="longColumn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="colorColumn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="legendColumn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="markers" type="{}Marker" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReportMap", propOrder = {
    "markerColor",
    "useDefaultSize",
    "height",
    "width",
    "isMapAllowedYN",
    "addAddressInDataYN",
    "addressColumn",
    "dataColumn",
    "defaultMapType",
    "latColumn",
    "longColumn",
    "colorColumn",
    "legendColumn",
    "markers"
})
public class ReportMap {

    protected String markerColor;
    protected String useDefaultSize;
    protected String height;
    protected String width;
    protected String isMapAllowedYN;
    protected String addAddressInDataYN;
    protected String addressColumn;
    protected String dataColumn;
    protected String defaultMapType;
    protected String latColumn;
    protected String longColumn;
    protected String colorColumn;
    protected String legendColumn;
    protected List<Marker> markers;

    /**
     * Gets the value of the markerColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarkerColor() {
        return markerColor;
    }

    /**
     * Sets the value of the markerColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarkerColor(String value) {
        this.markerColor = value;
    }

    /**
     * Gets the value of the useDefaultSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUseDefaultSize() {
        return useDefaultSize;
    }

    /**
     * Sets the value of the useDefaultSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUseDefaultSize(String value) {
        this.useDefaultSize = value;
    }

    /**
     * Gets the value of the height property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeight(String value) {
        this.height = value;
    }

    /**
     * Gets the value of the width property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWidth(String value) {
        this.width = value;
    }

    /**
     * Gets the value of the isMapAllowedYN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsMapAllowedYN() {
        return isMapAllowedYN;
    }

    /**
     * Sets the value of the isMapAllowedYN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsMapAllowedYN(String value) {
        this.isMapAllowedYN = value;
    }

    /**
     * Gets the value of the addAddressInDataYN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddAddressInDataYN() {
        return addAddressInDataYN;
    }

    /**
     * Sets the value of the addAddressInDataYN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddAddressInDataYN(String value) {
        this.addAddressInDataYN = value;
    }

    /**
     * Gets the value of the addressColumn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressColumn() {
        return addressColumn;
    }

    /**
     * Sets the value of the addressColumn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressColumn(String value) {
        this.addressColumn = value;
    }

    /**
     * Gets the value of the dataColumn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataColumn() {
        return dataColumn;
    }

    /**
     * Sets the value of the dataColumn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataColumn(String value) {
        this.dataColumn = value;
    }

    /**
     * Gets the value of the defaultMapType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultMapType() {
        return defaultMapType;
    }

    /**
     * Sets the value of the defaultMapType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultMapType(String value) {
        this.defaultMapType = value;
    }

    /**
     * Gets the value of the latColumn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLatColumn() {
        return latColumn;
    }

    /**
     * Sets the value of the latColumn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLatColumn(String value) {
        this.latColumn = value;
    }

    /**
     * Gets the value of the longColumn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLongColumn() {
        return longColumn;
    }

    /**
     * Sets the value of the longColumn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLongColumn(String value) {
        this.longColumn = value;
    }

    /**
     * Gets the value of the colorColumn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColorColumn() {
        return colorColumn;
    }

    /**
     * Sets the value of the colorColumn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColorColumn(String value) {
        this.colorColumn = value;
    }

    /**
     * Gets the value of the legendColumn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegendColumn() {
        return legendColumn;
    }

    /**
     * Sets the value of the legendColumn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegendColumn(String value) {
        this.legendColumn = value;
    }

    /**
     * Gets the value of the markers property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the markers property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMarkers().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Marker }
     * 
     * 
     */
    public List<Marker> getMarkers() {
        if (markers == null) {
            markers = new ArrayList<Marker>();
        }
        return this.markers;
    }

}
