/*
 * ============LICENSE_START==========================================
 * ONAP Portal SDK
 * ===================================================================
 * Copyright © 2017 AT&T Intellectual Property. All rights reserved.
 * ===================================================================
 *
 * Unless otherwise specified, all software contained herein is licensed
 * under the Apache License, Version 2.0 (the "License");
 * you may not use this software except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *             http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Unless otherwise specified, all documentation contained herein is licensed
 * under the Creative Commons License, Attribution 4.0 Intl. (the "License");
 * you may not use this documentation except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *             https://creativecommons.org/licenses/by/4.0/
 *
 * Unless required by applicable law or agreed to in writing, documentation
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * ============LICENSE_END============================================
 *
 * ECOMP is a trademark and service mark of AT&T Intellectual Property.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.07 at 02:07:29 PM EDT 
//


package org.onap.portalsdk.analytics.xmlobj;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ColFilterType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ColFilterType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="colId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="filterSeq" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="joinCondition" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="openBrackets" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="expression" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="argType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="argValue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="closeBrackets" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{}comment" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ColFilterType", propOrder = {
    "colId",
    "filterSeq",
    "joinCondition",
    "openBrackets",
    "expression",
    "argType",
    "argValue",
    "closeBrackets",
    "comment"
})
public class ColFilterType {

    @XmlElement(required = true)
    protected String colId;
    protected int filterSeq;
    @XmlElement(required = true)
    protected String joinCondition;
    protected String openBrackets;
    @XmlElement(required = true)
    protected String expression;
    protected String argType;
    protected String argValue;
    protected String closeBrackets;
    protected String comment;

    /**
     * Gets the value of the colId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColId() {
        return colId;
    }

    /**
     * Sets the value of the colId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColId(String value) {
        this.colId = value;
    }

    /**
     * Gets the value of the filterSeq property.
     * 
     */
    public int getFilterSeq() {
        return filterSeq;
    }

    /**
     * Sets the value of the filterSeq property.
     * 
     */
    public void setFilterSeq(int value) {
        this.filterSeq = value;
    }

    /**
     * Gets the value of the joinCondition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJoinCondition() {
        return joinCondition;
    }

    /**
     * Sets the value of the joinCondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJoinCondition(String value) {
        this.joinCondition = value;
    }

    /**
     * Gets the value of the openBrackets property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpenBrackets() {
        return openBrackets;
    }

    /**
     * Sets the value of the openBrackets property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpenBrackets(String value) {
        this.openBrackets = value;
    }

    /**
     * Gets the value of the expression property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpression() {
        return expression;
    }

    /**
     * Sets the value of the expression property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpression(String value) {
        this.expression = value;
    }

    /**
     * Gets the value of the argType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArgType() {
        return argType;
    }

    /**
     * Sets the value of the argType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArgType(String value) {
        this.argType = value;
    }

    /**
     * Gets the value of the argValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArgValue() {
        return argValue;
    }

    /**
     * Sets the value of the argValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArgValue(String value) {
        this.argValue = value;
    }

    /**
     * Gets the value of the closeBrackets property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCloseBrackets() {
        return closeBrackets;
    }

    /**
     * Sets the value of the closeBrackets property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCloseBrackets(String value) {
        this.closeBrackets = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }

}
