/*
 * ============LICENSE_START==========================================
 * ONAP Portal SDK
 * ===================================================================
 * Copyright © 2017 AT&T Intellectual Property. All rights reserved.
 * ===================================================================
 *
 * Unless otherwise specified, all software contained herein is licensed
 * under the Apache License, Version 2.0 (the “License”);
 * you may not use this software except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *             http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Unless otherwise specified, all documentation contained herein is licensed
 * under the Creative Commons License, Attribution 4.0 Intl. (the “License”);
 * you may not use this documentation except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *             https://creativecommons.org/licenses/by/4.0/
 *
 * Unless required by applicable law or agreed to in writing, documentation
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * ============LICENSE_END============================================
 *
 * ECOMP is a trademark and service mark of AT&T Intellectual Property.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.07 at 02:07:29 PM EDT 
//


package org.onap.portalsdk.analytics.xmlobj;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for CustomReportType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CustomReportType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="reportName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="reportDescr" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="numDashCols" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dashboardLayoutHTML" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dbInfo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dbType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="chartType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="chartTypeFixed" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="chartMultiSeries" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="chartLeftAxisLabel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="chartRightAxisLabel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="chartWidth" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="chartHeight" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="showChartTitle" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="public" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="hideFormFieldAfterRun" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="createId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="createDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="reportSQL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="reportTitle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="reportSubTitle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="reportHeader" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="frozenColumns" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="pdfImgLogo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="emptyMessage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="widthNoColumn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dataGridAlign" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="reportFooter" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="numFormCols" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="displayOptions" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="jumpTo" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="searchPageSize" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="navPosition" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="toggleLayout" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="pageNav" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="showPageSize" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="showNavPos" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="showGotoOption" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="dataContainerHeight" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dataContainerWidth" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="allowSchedule" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="multiGroupColumn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="topDown" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sizedByContent" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{}comment" minOccurs="0"/>
 *         &lt;element name="dataSourceList" type="{}DataSourceList" minOccurs="0"/>
 *         &lt;element name="formFieldList" type="{}FormFieldList" minOccurs="0"/>
 *         &lt;element name="javascriptList" type="{}JavascriptList" minOccurs="0"/>
 *         &lt;element name="semaphoreList" type="{}SemaphoreList" minOccurs="0"/>
 *         &lt;element name="dashboardOptions" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dashboardType" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="reportInNewWindow" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="displayFolderTree" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="maxRowsInExcelDownload" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="dashBoardReports" type="{}DashboardReports" minOccurs="0"/>
 *         &lt;element name="dashBoardReportsNew" type="{}DashboardReportsNew" minOccurs="0"/>
 *         &lt;element name="chartAdditionalOptions" type="{}ChartAdditionalOptions" minOccurs="0"/>
 *         &lt;element name="pdfAdditionalOptions" type="{}PDFAdditionalOptions" minOccurs="0"/>
 *         &lt;element name="chartDrillOptions" type="{}ChartDrillOptions" minOccurs="0"/>
 *         &lt;element name="dataminingOptions" type="{}DataminingOptions" minOccurs="0"/>
 *         &lt;element name="javascriptElement" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="folderId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="drillURLInPoPUpPresent" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="isOneTimeScheduleAllowed" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="isHourlyScheduleAllowed" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="isDailyScheduleAllowed" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="isDailyMFScheduleAllowed" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="isWeeklyScheduleAllowed" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="isMonthlyScheduleAllowed" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="reportMap" type="{}ReportMap" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="pageSize" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="reportType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CustomReportType", propOrder = {
    "reportName",
    "reportDescr",
    "numDashCols",
    "dashboardLayoutHTML",
    "dbInfo",
    "dbType",
    "chartType",
    "chartTypeFixed",
    "chartMultiSeries",
    "chartLeftAxisLabel",
    "chartRightAxisLabel",
    "chartWidth",
    "chartHeight",
    "showChartTitle",
    "_public",
    "hideFormFieldAfterRun",
    "createId",
    "createDate",
    "reportSQL",
    "reportTitle",
    "reportSubTitle",
    "reportHeader",
    "frozenColumns",
    "pdfImgLogo",
    "emptyMessage",
    "widthNoColumn",
    "dataGridAlign",
    "reportFooter",
    "numFormCols",
    "displayOptions",
    "jumpTo",
    "searchPageSize",
    "navPosition",
    "toggleLayout",
    "pageNav",
    "showPageSize",
    "showNavPos",
    "showGotoOption",
    "dataContainerHeight",
    "dataContainerWidth",
    "allowSchedule",
    "multiGroupColumn",
    "topDown",
    "sizedByContent",
    "comment",
    "dataSourceList",
    "formFieldList",
    "javascriptList",
    "semaphoreList",
    "dashboardOptions",
    "dashboardType",
    "reportInNewWindow",
    "displayFolderTree",
    "maxRowsInExcelDownload",
    "dashBoardReports",
    "dashBoardReportsNew",
    "chartAdditionalOptions",
    "pdfAdditionalOptions",
    "chartDrillOptions",
    "dataminingOptions",
    "javascriptElement",
    "folderId",
    "drillURLInPoPUpPresent",
    "isOneTimeScheduleAllowed",
    "isHourlyScheduleAllowed",
    "isDailyScheduleAllowed",
    "isDailyMFScheduleAllowed",
    "isWeeklyScheduleAllowed",
    "isMonthlyScheduleAllowed",
    "reportMap"
})
public class CustomReportType {

    @XmlElement(required = true)
    protected String reportName;
    @XmlElement(required = true)
    protected String reportDescr;
    protected String numDashCols;
    protected String dashboardLayoutHTML;
    protected String dbInfo;
    protected String dbType;
    @XmlElement(required = true)
    protected String chartType;
    protected String chartTypeFixed;
    protected String chartMultiSeries;
    protected String chartLeftAxisLabel;
    protected String chartRightAxisLabel;
    protected String chartWidth;
    protected String chartHeight;
    @XmlElement(defaultValue = "false")
    protected boolean showChartTitle;
    @XmlElement(name = "public", defaultValue = "false")
    protected boolean _public;
    @XmlElement(defaultValue = "false")
    protected Boolean hideFormFieldAfterRun;
    @XmlElement(required = true)
    protected String createId;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar createDate;
    protected String reportSQL;
    protected String reportTitle;
    protected String reportSubTitle;
    protected String reportHeader;
    @XmlElement(defaultValue = "0")
    protected Integer frozenColumns;
    protected String pdfImgLogo;
    protected String emptyMessage;
    protected String widthNoColumn;
    protected String dataGridAlign;
    protected String reportFooter;
    protected String numFormCols;
    protected String displayOptions;
    protected Integer jumpTo;
    protected Integer searchPageSize;
    protected String navPosition;
    @XmlElement(defaultValue = "true")
    protected Boolean toggleLayout;
    @XmlElement(defaultValue = "true")
    protected Boolean pageNav;
    @XmlElement(defaultValue = "true")
    protected Boolean showPageSize;
    @XmlElement(defaultValue = "true")
    protected Boolean showNavPos;
    @XmlElement(defaultValue = "true")
    protected Boolean showGotoOption;
    protected String dataContainerHeight;
    protected String dataContainerWidth;
    protected String allowSchedule;
    protected String multiGroupColumn;
    protected String topDown;
    protected String sizedByContent;
    protected String comment;
    protected DataSourceList dataSourceList;
    protected FormFieldList formFieldList;
    protected JavascriptList javascriptList;
    protected SemaphoreList semaphoreList;
    protected String dashboardOptions;
    @XmlElement(defaultValue = "false")
    protected Boolean dashboardType;
    @XmlElement(defaultValue = "false")
    protected Boolean reportInNewWindow;
    @XmlElement(defaultValue = "false")
    protected Boolean displayFolderTree;
    protected Integer maxRowsInExcelDownload;
    protected DashboardReports dashBoardReports;
    protected DashboardReportsNew dashBoardReportsNew;
    protected ChartAdditionalOptions chartAdditionalOptions;
    protected PDFAdditionalOptions pdfAdditionalOptions;
    protected ChartDrillOptions chartDrillOptions;
    protected DataminingOptions dataminingOptions;
    protected String javascriptElement;
    @XmlElement(defaultValue = "0")
    protected String folderId;
    @XmlElement(defaultValue = "false")
    protected Boolean drillURLInPoPUpPresent;
    protected String isOneTimeScheduleAllowed;
    protected String isHourlyScheduleAllowed;
    protected String isDailyScheduleAllowed;
    protected String isDailyMFScheduleAllowed;
    protected String isWeeklyScheduleAllowed;
    protected String isMonthlyScheduleAllowed;
    protected ReportMap reportMap;
    @XmlAttribute(name = "pageSize")
    protected Integer pageSize;
    @XmlAttribute(name = "reportType")
    protected String reportType;

    /**
     * Gets the value of the reportName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportName() {
        return reportName;
    }

    /**
     * Sets the value of the reportName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportName(String value) {
        this.reportName = value;
    }

    /**
     * Gets the value of the reportDescr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportDescr() {
        return reportDescr;
    }

    /**
     * Sets the value of the reportDescr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportDescr(String value) {
        this.reportDescr = value;
    }

    /**
     * Gets the value of the numDashCols property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumDashCols() {
        return numDashCols;
    }

    /**
     * Sets the value of the numDashCols property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumDashCols(String value) {
        this.numDashCols = value;
    }

    /**
     * Gets the value of the dashboardLayoutHTML property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDashboardLayoutHTML() {
        return dashboardLayoutHTML;
    }

    /**
     * Sets the value of the dashboardLayoutHTML property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDashboardLayoutHTML(String value) {
        this.dashboardLayoutHTML = value;
    }

    /**
     * Gets the value of the dbInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDbInfo() {
        return dbInfo;
    }

    /**
     * Sets the value of the dbInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDbInfo(String value) {
        this.dbInfo = value;
    }

    /**
     * Gets the value of the dbType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDbType() {
        return dbType;
    }

    /**
     * Sets the value of the dbType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDbType(String value) {
        this.dbType = value;
    }

    /**
     * Gets the value of the chartType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChartType() {
        return chartType;
    }

    /**
     * Sets the value of the chartType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChartType(String value) {
        this.chartType = value;
    }

    /**
     * Gets the value of the chartTypeFixed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChartTypeFixed() {
        return chartTypeFixed;
    }

    /**
     * Sets the value of the chartTypeFixed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChartTypeFixed(String value) {
        this.chartTypeFixed = value;
    }

    /**
     * Gets the value of the chartMultiSeries property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChartMultiSeries() {
        return chartMultiSeries;
    }

    /**
     * Sets the value of the chartMultiSeries property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChartMultiSeries(String value) {
        this.chartMultiSeries = value;
    }

    /**
     * Gets the value of the chartLeftAxisLabel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChartLeftAxisLabel() {
        return chartLeftAxisLabel;
    }

    /**
     * Sets the value of the chartLeftAxisLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChartLeftAxisLabel(String value) {
        this.chartLeftAxisLabel = value;
    }

    /**
     * Gets the value of the chartRightAxisLabel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChartRightAxisLabel() {
        return chartRightAxisLabel;
    }

    /**
     * Sets the value of the chartRightAxisLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChartRightAxisLabel(String value) {
        this.chartRightAxisLabel = value;
    }

    /**
     * Gets the value of the chartWidth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChartWidth() {
        return chartWidth;
    }

    /**
     * Sets the value of the chartWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChartWidth(String value) {
        this.chartWidth = value;
    }

    /**
     * Gets the value of the chartHeight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChartHeight() {
        return chartHeight;
    }

    /**
     * Sets the value of the chartHeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChartHeight(String value) {
        this.chartHeight = value;
    }

    /**
     * Gets the value of the showChartTitle property.
     * 
     */
    public boolean isShowChartTitle() {
        return showChartTitle;
    }

    /**
     * Sets the value of the showChartTitle property.
     * 
     */
    public void setShowChartTitle(boolean value) {
        this.showChartTitle = value;
    }

    /**
     * Gets the value of the public property.
     * 
     */
    public boolean isPublic() {
        return _public;
    }

    /**
     * Sets the value of the public property.
     * 
     */
    public void setPublic(boolean value) {
        this._public = value;
    }

    /**
     * Gets the value of the hideFormFieldAfterRun property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHideFormFieldAfterRun() {
        return hideFormFieldAfterRun;
    }

    /**
     * Sets the value of the hideFormFieldAfterRun property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHideFormFieldAfterRun(Boolean value) {
        this.hideFormFieldAfterRun = value;
    }

    /**
     * Gets the value of the createId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreateId() {
        return createId;
    }

    /**
     * Sets the value of the createId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreateId(String value) {
        this.createId = value;
    }

    /**
     * Gets the value of the createDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreateDate() {
        return createDate;
    }

    /**
     * Sets the value of the createDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreateDate(XMLGregorianCalendar value) {
        this.createDate = value;
    }

    /**
     * Gets the value of the reportSQL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportSQL() {
        return reportSQL;
    }

    /**
     * Sets the value of the reportSQL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportSQL(String value) {
        this.reportSQL = value;
    }

    /**
     * Gets the value of the reportTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportTitle() {
        return reportTitle;
    }

    /**
     * Sets the value of the reportTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportTitle(String value) {
        this.reportTitle = value;
    }

    /**
     * Gets the value of the reportSubTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportSubTitle() {
        return reportSubTitle;
    }

    /**
     * Sets the value of the reportSubTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportSubTitle(String value) {
        this.reportSubTitle = value;
    }

    /**
     * Gets the value of the reportHeader property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportHeader() {
        return reportHeader;
    }

    /**
     * Sets the value of the reportHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportHeader(String value) {
        this.reportHeader = value;
    }

    /**
     * Gets the value of the frozenColumns property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFrozenColumns() {
        return frozenColumns;
    }

    /**
     * Sets the value of the frozenColumns property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFrozenColumns(Integer value) {
        this.frozenColumns = value;
    }

    /**
     * Gets the value of the pdfImgLogo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPdfImgLogo() {
        return pdfImgLogo;
    }

    /**
     * Sets the value of the pdfImgLogo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPdfImgLogo(String value) {
        this.pdfImgLogo = value;
    }

    /**
     * Gets the value of the emptyMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmptyMessage() {
        return emptyMessage;
    }

    /**
     * Sets the value of the emptyMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmptyMessage(String value) {
        this.emptyMessage = value;
    }

    /**
     * Gets the value of the widthNoColumn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWidthNoColumn() {
        return widthNoColumn;
    }

    /**
     * Sets the value of the widthNoColumn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWidthNoColumn(String value) {
        this.widthNoColumn = value;
    }

    /**
     * Gets the value of the dataGridAlign property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataGridAlign() {
        return dataGridAlign;
    }

    /**
     * Sets the value of the dataGridAlign property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataGridAlign(String value) {
        this.dataGridAlign = value;
    }

    /**
     * Gets the value of the reportFooter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportFooter() {
        return reportFooter;
    }

    /**
     * Sets the value of the reportFooter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportFooter(String value) {
        this.reportFooter = value;
    }

    /**
     * Gets the value of the numFormCols property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumFormCols() {
        return numFormCols;
    }

    /**
     * Sets the value of the numFormCols property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumFormCols(String value) {
        this.numFormCols = value;
    }

    /**
     * Gets the value of the displayOptions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayOptions() {
        return displayOptions;
    }

    /**
     * Sets the value of the displayOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayOptions(String value) {
        this.displayOptions = value;
    }

    /**
     * Gets the value of the jumpTo property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getJumpTo() {
        return jumpTo;
    }

    /**
     * Sets the value of the jumpTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setJumpTo(Integer value) {
        this.jumpTo = value;
    }

    /**
     * Gets the value of the searchPageSize property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSearchPageSize() {
        return searchPageSize;
    }

    /**
     * Sets the value of the searchPageSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSearchPageSize(Integer value) {
        this.searchPageSize = value;
    }

    /**
     * Gets the value of the navPosition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNavPosition() {
        return navPosition;
    }

    /**
     * Sets the value of the navPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNavPosition(String value) {
        this.navPosition = value;
    }

    /**
     * Gets the value of the toggleLayout property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isToggleLayout() {
        return toggleLayout;
    }

    /**
     * Sets the value of the toggleLayout property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setToggleLayout(Boolean value) {
        this.toggleLayout = value;
    }

    /**
     * Gets the value of the pageNav property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPageNav() {
        return pageNav;
    }

    /**
     * Sets the value of the pageNav property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPageNav(Boolean value) {
        this.pageNav = value;
    }

    /**
     * Gets the value of the showPageSize property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isShowPageSize() {
        return showPageSize;
    }

    /**
     * Sets the value of the showPageSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShowPageSize(Boolean value) {
        this.showPageSize = value;
    }

    /**
     * Gets the value of the showNavPos property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isShowNavPos() {
        return showNavPos;
    }

    /**
     * Sets the value of the showNavPos property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShowNavPos(Boolean value) {
        this.showNavPos = value;
    }

    /**
     * Gets the value of the showGotoOption property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isShowGotoOption() {
        return showGotoOption;
    }

    /**
     * Sets the value of the showGotoOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShowGotoOption(Boolean value) {
        this.showGotoOption = value;
    }

    /**
     * Gets the value of the dataContainerHeight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataContainerHeight() {
        return dataContainerHeight;
    }

    /**
     * Sets the value of the dataContainerHeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataContainerHeight(String value) {
        this.dataContainerHeight = value;
    }

    /**
     * Gets the value of the dataContainerWidth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataContainerWidth() {
        return dataContainerWidth;
    }

    /**
     * Sets the value of the dataContainerWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataContainerWidth(String value) {
        this.dataContainerWidth = value;
    }

    /**
     * Gets the value of the allowSchedule property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAllowSchedule() {
        return allowSchedule;
    }

    /**
     * Sets the value of the allowSchedule property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAllowSchedule(String value) {
        this.allowSchedule = value;
    }

    /**
     * Gets the value of the multiGroupColumn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMultiGroupColumn() {
        return multiGroupColumn;
    }

    /**
     * Sets the value of the multiGroupColumn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMultiGroupColumn(String value) {
        this.multiGroupColumn = value;
    }

    /**
     * Gets the value of the topDown property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTopDown() {
        return topDown;
    }

    /**
     * Sets the value of the topDown property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTopDown(String value) {
        this.topDown = value;
    }

    /**
     * Gets the value of the sizedByContent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSizedByContent() {
        return sizedByContent;
    }

    /**
     * Sets the value of the sizedByContent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSizedByContent(String value) {
        this.sizedByContent = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }

    /**
     * Gets the value of the dataSourceList property.
     * 
     * @return
     *     possible object is
     *     {@link DataSourceList }
     *     
     */
    public DataSourceList getDataSourceList() {
        return dataSourceList;
    }

    /**
     * Sets the value of the dataSourceList property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataSourceList }
     *     
     */
    public void setDataSourceList(DataSourceList value) {
        this.dataSourceList = value;
    }

    /**
     * Gets the value of the formFieldList property.
     * 
     * @return
     *     possible object is
     *     {@link FormFieldList }
     *     
     */
    public FormFieldList getFormFieldList() {
        return formFieldList;
    }

    /**
     * Sets the value of the formFieldList property.
     * 
     * @param value
     *     allowed object is
     *     {@link FormFieldList }
     *     
     */
    public void setFormFieldList(FormFieldList value) {
        this.formFieldList = value;
    }

    /**
     * Gets the value of the javascriptList property.
     * 
     * @return
     *     possible object is
     *     {@link JavascriptList }
     *     
     */
    public JavascriptList getJavascriptList() {
        return javascriptList;
    }

    /**
     * Sets the value of the javascriptList property.
     * 
     * @param value
     *     allowed object is
     *     {@link JavascriptList }
     *     
     */
    public void setJavascriptList(JavascriptList value) {
        this.javascriptList = value;
    }

    /**
     * Gets the value of the semaphoreList property.
     * 
     * @return
     *     possible object is
     *     {@link SemaphoreList }
     *     
     */
    public SemaphoreList getSemaphoreList() {
        return semaphoreList;
    }

    /**
     * Sets the value of the semaphoreList property.
     * 
     * @param value
     *     allowed object is
     *     {@link SemaphoreList }
     *     
     */
    public void setSemaphoreList(SemaphoreList value) {
        this.semaphoreList = value;
    }

    /**
     * Gets the value of the dashboardOptions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDashboardOptions() {
        return dashboardOptions;
    }

    /**
     * Sets the value of the dashboardOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDashboardOptions(String value) {
        this.dashboardOptions = value;
    }

    /**
     * Gets the value of the dashboardType property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDashboardType() {
        return dashboardType;
    }

    /**
     * Sets the value of the dashboardType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDashboardType(Boolean value) {
        this.dashboardType = value;
    }

    /**
     * Gets the value of the reportInNewWindow property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isReportInNewWindow() {
        return reportInNewWindow;
    }

    /**
     * Sets the value of the reportInNewWindow property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setReportInNewWindow(Boolean value) {
        this.reportInNewWindow = value;
    }

    /**
     * Gets the value of the displayFolderTree property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDisplayFolderTree() {
        return displayFolderTree;
    }

    /**
     * Sets the value of the displayFolderTree property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDisplayFolderTree(Boolean value) {
        this.displayFolderTree = value;
    }

    /**
     * Gets the value of the maxRowsInExcelDownload property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxRowsInExcelDownload() {
        return maxRowsInExcelDownload;
    }

    /**
     * Sets the value of the maxRowsInExcelDownload property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxRowsInExcelDownload(Integer value) {
        this.maxRowsInExcelDownload = value;
    }

    /**
     * Gets the value of the dashBoardReports property.
     * 
     * @return
     *     possible object is
     *     {@link DashboardReports }
     *     
     */
    public DashboardReports getDashBoardReports() {
        return dashBoardReports;
    }

    /**
     * Sets the value of the dashBoardReports property.
     * 
     * @param value
     *     allowed object is
     *     {@link DashboardReports }
     *     
     */
    public void setDashBoardReports(DashboardReports value) {
        this.dashBoardReports = value;
    }

    /**
     * Gets the value of the dashBoardReportsNew property.
     * 
     * @return
     *     possible object is
     *     {@link DashboardReportsNew }
     *     
     */
    public DashboardReportsNew getDashBoardReportsNew() {
        return dashBoardReportsNew;
    }

    /**
     * Sets the value of the dashBoardReportsNew property.
     * 
     * @param value
     *     allowed object is
     *     {@link DashboardReportsNew }
     *     
     */
    public void setDashBoardReportsNew(DashboardReportsNew value) {
        this.dashBoardReportsNew = value;
    }

    /**
     * Gets the value of the chartAdditionalOptions property.
     * 
     * @return
     *     possible object is
     *     {@link ChartAdditionalOptions }
     *     
     */
    public ChartAdditionalOptions getChartAdditionalOptions() {
        return chartAdditionalOptions;
    }

    /**
     * Sets the value of the chartAdditionalOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChartAdditionalOptions }
     *     
     */
    public void setChartAdditionalOptions(ChartAdditionalOptions value) {
        this.chartAdditionalOptions = value;
    }

    /**
     * Gets the value of the pdfAdditionalOptions property.
     * 
     * @return
     *     possible object is
     *     {@link PDFAdditionalOptions }
     *     
     */
    public PDFAdditionalOptions getPdfAdditionalOptions() {
        return pdfAdditionalOptions;
    }

    /**
     * Sets the value of the pdfAdditionalOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link PDFAdditionalOptions }
     *     
     */
    public void setPdfAdditionalOptions(PDFAdditionalOptions value) {
        this.pdfAdditionalOptions = value;
    }

    /**
     * Gets the value of the chartDrillOptions property.
     * 
     * @return
     *     possible object is
     *     {@link ChartDrillOptions }
     *     
     */
    public ChartDrillOptions getChartDrillOptions() {
        return chartDrillOptions;
    }

    /**
     * Sets the value of the chartDrillOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChartDrillOptions }
     *     
     */
    public void setChartDrillOptions(ChartDrillOptions value) {
        this.chartDrillOptions = value;
    }

    /**
     * Gets the value of the dataminingOptions property.
     * 
     * @return
     *     possible object is
     *     {@link DataminingOptions }
     *     
     */
    public DataminingOptions getDataminingOptions() {
        return dataminingOptions;
    }

    /**
     * Sets the value of the dataminingOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataminingOptions }
     *     
     */
    public void setDataminingOptions(DataminingOptions value) {
        this.dataminingOptions = value;
    }

    /**
     * Gets the value of the javascriptElement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJavascriptElement() {
        return javascriptElement;
    }

    /**
     * Sets the value of the javascriptElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJavascriptElement(String value) {
        this.javascriptElement = value;
    }

    /**
     * Gets the value of the folderId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFolderId() {
        return folderId;
    }

    /**
     * Sets the value of the folderId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFolderId(String value) {
        this.folderId = value;
    }

    /**
     * Gets the value of the drillURLInPoPUpPresent property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDrillURLInPoPUpPresent() {
        return drillURLInPoPUpPresent;
    }

    /**
     * Sets the value of the drillURLInPoPUpPresent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDrillURLInPoPUpPresent(Boolean value) {
        this.drillURLInPoPUpPresent = value;
    }

    /**
     * Gets the value of the isOneTimeScheduleAllowed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsOneTimeScheduleAllowed() {
        return isOneTimeScheduleAllowed;
    }

    /**
     * Sets the value of the isOneTimeScheduleAllowed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsOneTimeScheduleAllowed(String value) {
        this.isOneTimeScheduleAllowed = value;
    }

    /**
     * Gets the value of the isHourlyScheduleAllowed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsHourlyScheduleAllowed() {
        return isHourlyScheduleAllowed;
    }

    /**
     * Sets the value of the isHourlyScheduleAllowed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsHourlyScheduleAllowed(String value) {
        this.isHourlyScheduleAllowed = value;
    }

    /**
     * Gets the value of the isDailyScheduleAllowed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsDailyScheduleAllowed() {
        return isDailyScheduleAllowed;
    }

    /**
     * Sets the value of the isDailyScheduleAllowed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsDailyScheduleAllowed(String value) {
        this.isDailyScheduleAllowed = value;
    }

    /**
     * Gets the value of the isDailyMFScheduleAllowed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsDailyMFScheduleAllowed() {
        return isDailyMFScheduleAllowed;
    }

    /**
     * Sets the value of the isDailyMFScheduleAllowed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsDailyMFScheduleAllowed(String value) {
        this.isDailyMFScheduleAllowed = value;
    }

    /**
     * Gets the value of the isWeeklyScheduleAllowed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsWeeklyScheduleAllowed() {
        return isWeeklyScheduleAllowed;
    }

    /**
     * Sets the value of the isWeeklyScheduleAllowed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsWeeklyScheduleAllowed(String value) {
        this.isWeeklyScheduleAllowed = value;
    }

    /**
     * Gets the value of the isMonthlyScheduleAllowed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsMonthlyScheduleAllowed() {
        return isMonthlyScheduleAllowed;
    }

    /**
     * Sets the value of the isMonthlyScheduleAllowed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsMonthlyScheduleAllowed(String value) {
        this.isMonthlyScheduleAllowed = value;
    }

    /**
     * Gets the value of the reportMap property.
     * 
     * @return
     *     possible object is
     *     {@link ReportMap }
     *     
     */
    public ReportMap getReportMap() {
        return reportMap;
    }

    /**
     * Sets the value of the reportMap property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReportMap }
     *     
     */
    public void setReportMap(ReportMap value) {
        this.reportMap = value;
    }

    /**
     * Gets the value of the pageSize property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPageSize() {
        return pageSize;
    }

    /**
     * Sets the value of the pageSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPageSize(Integer value) {
        this.pageSize = value;
    }

    /**
     * Gets the value of the reportType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportType() {
        return reportType;
    }

    /**
     * Sets the value of the reportType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportType(String value) {
        this.reportType = value;
    }

}
